CREATE TABLE IF NOT EXISTS cidades ( 
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  estado_id INT NOT NULL,
  area NUMERIC(10, 2),
  FOREIGN KEY (estado_id) REFERENCES estados(id)
); --Criando tabela cidades

select * from estados e, cidades c where e.id = c.estado_id; --Trazendo as duas tabelas sem filtros

select e.nome as "Estado", c.nome as "Cidade", regiao as "Região" from estados e, cidades c where e.id = c.estado_id; --Filtrando as tabelas

select  c.nome as "Cidade", e.nome as "Estado", regiao as "Região" from estados e inner join cidades c on e.id = c.estado_id --Filtrando pelo inner join

insert into cidades (nome, area, estado_id) values ('Campinas',795,31) --Inserindo cidades sabendo qual é a posição do estado

insert into cidades (nome, area, estado_id) values ('Niterói',133.9,27) 

INSERT INTO cidades (nome, area, estado_id) VALUES ('Caruaru', 920.6, (SELECT id FROM estados WHERE sigla = 'PE')) --Inserindo cidades sem saber qual é a posição do estado e sim pela a sigla

INSERT INTO cidades (nome, area, estado_id) VALUES ('Juazeiro do Norte', 248.2, (SELECT id FROM estados WHERE sigla = 'CE'))


INSERT INTO cidades (nome, area, estado_id) VALUES 
('Rio Branco', 9.2, (SELECT id FROM estados WHERE sigla = 'AC')),
('Cruzeiro do Sul', 7.9, (SELECT id FROM estados WHERE sigla = 'AC')),
('Sena Madureira', 25.2, (SELECT id FROM estados WHERE sigla = 'AC')),
('Tarauacá', 15.5, (SELECT id FROM estados WHERE sigla = 'AC')),
('Feijó', 24.2, (SELECT id FROM estados WHERE sigla = 'AC')),
('Maceió', 9.2, (SELECT id FROM estados WHERE sigla = 'AL')),
('Arapiraca', 7.9, (SELECT id FROM estados WHERE sigla = 'AL')),
('Rio Largo', 25.2, (SELECT id FROM estados WHERE sigla = 'AL')),
('Palmeira dos Índios', 15.5, (SELECT id FROM estados WHERE sigla = 'AL')),
('União dos Palmares', 24.2, (SELECT id FROM estados WHERE sigla = 'AL')),
('Macapá', 9.2, (SELECT id FROM estados WHERE sigla = 'AP')),
('Santana', 7.9, (SELECT id FROM estados WHERE sigla = 'AP')),
('Laranjal do Jari', 25.2, (SELECT id FROM estados WHERE sigla = 'AP')),
('Oiapoque', 15.5, (SELECT id FROM estados WHERE sigla = 'AP')),
('Mazagão', 24.2, (SELECT id FROM estados WHERE sigla = 'AP')),
('Manaus', 9.2, (SELECT id FROM estados WHERE sigla = 'AM')),
('Parintins', 7.9, (SELECT id FROM estados WHERE sigla = 'AM')),
('Itacoatiara', 25.2, (SELECT id FROM estados WHERE sigla = 'AM')),
('Manacapuru', 15.5, (SELECT id FROM estados WHERE sigla = 'AM')),
('Coari', 24.2, (SELECT id FROM estados WHERE sigla = 'AM')),
('Salvador', 50.6, (SELECT id FROM estados WHERE sigla = 'BA')),
('Feira de Santana', 7.9, (SELECT id FROM estados WHERE sigla = 'BA')),
('Vitória da Conquista', 25.2, (SELECT id FROM estados WHERE sigla = 'BA')),
('Camaçari', 15.5, (SELECT id FROM estados WHERE sigla = 'BA')),
('Itabuna', 24.2, (SELECT id FROM estados WHERE sigla = 'BA')),
('Fortaleza', 9.2, (SELECT id FROM estados WHERE sigla = 'CE')),
('Caucaia', 25.2, (SELECT id FROM estados WHERE sigla = 'CE')),
('Maracanaú', 15.5, (SELECT id FROM estados WHERE sigla = 'CE')),
('Sobral', 24.2, (SELECT id FROM estados WHERE sigla = 'CE')),
('Brasília', 7.9, (SELECT id FROM estados WHERE sigla = 'DF')),
('Serra', 25.2, (SELECT id FROM estados WHERE sigla = 'ES')),
('Vila Velha', 15.5, (SELECT id FROM estados WHERE sigla = 'ES')),
('Cariacica', 24.2, (SELECT id FROM estados WHERE sigla = 'ES')),
('Vitória', 24.2, (SELECT id FROM estados WHERE sigla = 'ES')),
('Cachoeira de Itapemirim', 9.2, (SELECT id FROM estados WHERE sigla = 'ES')),
('Goiânia', 50.6, (SELECT id FROM estados WHERE sigla = 'GO')),
('Aparecida de Goiânia', 7.9, (SELECT id FROM estados WHERE sigla = 'GO')),
('Anápolis', 25.2, (SELECT id FROM estados WHERE sigla = 'GO')),
('Rio Verde', 15.5, (SELECT id FROM estados WHERE sigla = 'GO')),
('Luziânia', 24.2, (SELECT id FROM estados WHERE sigla = 'GO')),
('São Luís', 9.2, (SELECT id FROM estados WHERE sigla = 'MA')),
('Imperatriz', 25.2, (SELECT id FROM estados WHERE sigla = 'MA')),
('São José do Ribamar', 15.5, (SELECT id FROM estados WHERE sigla = 'MA')),
('Caxias', 24.2, (SELECT id FROM estados WHERE sigla = 'MA')),
('Timon', 7.9, (SELECT id FROM estados WHERE sigla = 'MA')),
('Cuiabá', 25.2, (SELECT id FROM estados WHERE sigla = 'MT')),
('Várzea Grande', 15.5, (SELECT id FROM estados WHERE sigla = 'MT')),
('Rondonópolis', 24.2, (SELECT id FROM estados WHERE sigla = 'MT')),
('Sinop', 24.2, (SELECT id FROM estados WHERE sigla = 'MT')),
('Tangará da Serra', 9.2, (SELECT id FROM estados WHERE sigla = 'MT')),
('Campo Grande', 50.6, (SELECT id FROM estados WHERE sigla = 'MS')),
('Dourados', 7.9, (SELECT id FROM estados WHERE sigla = 'MS')),
('Três Lagoas', 25.2, (SELECT id FROM estados WHERE sigla = 'MS')),
('Corumbá', 15.5, (SELECT id FROM estados WHERE sigla = 'MS')),
('Ponta Porã', 24.2, (SELECT id FROM estados WHERE sigla = 'MS')),
('Belo Horizonte', 9.2, (SELECT id FROM estados WHERE sigla = 'MG')),
('Uberlândia', 25.2, (SELECT id FROM estados WHERE sigla = 'MG')),
('Contagem', 15.5, (SELECT id FROM estados WHERE sigla = 'MG')),
('Juiz de Fora', 24.2, (SELECT id FROM estados WHERE sigla = 'MG')),
('Betim', 7.9, (SELECT id FROM estados WHERE sigla = 'MG')),
('Belém', 25.2, (SELECT id FROM estados WHERE sigla = 'PA')),
('Ananindeua', 15.5, (SELECT id FROM estados WHERE sigla = 'PA')),
('Santarém', 24.2, (SELECT id FROM estados WHERE sigla = 'PA')),
('Marabá', 24.2, (SELECT id FROM estados WHERE sigla = 'PA')),
('Parauapebas', 9.2, (SELECT id FROM estados WHERE sigla = 'PA')),
('João Pessoa', 50.6, (SELECT id FROM estados WHERE sigla = 'PB')),
('Campina Grande', 7.9, (SELECT id FROM estados WHERE sigla = 'PB')),
('Santa Rita', 25.2, (SELECT id FROM estados WHERE sigla = 'PB')),
('Patos', 15.5, (SELECT id FROM estados WHERE sigla = 'PB')),
('Bayeux', 24.2, (SELECT id FROM estados WHERE sigla = 'PB')),
('Curitiba', 9.2, (SELECT id FROM estados WHERE sigla = 'PR')),
('Londrina', 25.2, (SELECT id FROM estados WHERE sigla = 'PR')),
('Maringá', 15.5, (SELECT id FROM estados WHERE sigla = 'PR')),
('Ponta Grossa', 24.2, (SELECT id FROM estados WHERE sigla = 'PR')),
('Cascavel', 7.9, (SELECT id FROM estados WHERE sigla = 'PR')),
('Recife', 25.2, (SELECT id FROM estados WHERE sigla = 'PE')),
('Jaboatão dos Guararapes', 15.5, (SELECT id FROM estados WHERE sigla = 'PE')),
('Olinda', 24.2, (SELECT id FROM estados WHERE sigla = 'PE')),
('Petrolina', 9.2, (SELECT id FROM estados WHERE sigla = 'PE')),
('Teresina', 50.6, (SELECT id FROM estados WHERE sigla = 'PI')),
('Parnaíba', 7.9, (SELECT id FROM estados WHERE sigla = 'PI')),
('Picos', 25.2, (SELECT id FROM estados WHERE sigla = 'PI')),
('Piripiri', 15.5, (SELECT id FROM estados WHERE sigla = 'PI')),
('Floriano', 24.2, (SELECT id FROM estados WHERE sigla = 'PI')),
('Rio de Janeiro', 9.2, (SELECT id FROM estados WHERE sigla = 'RJ')),
('São Gonçalo', 25.2, (SELECT id FROM estados WHERE sigla = 'RJ')),
('Duque de Caxias', 15.5, (SELECT id FROM estados WHERE sigla = 'RJ')),
('Nova Iguaçu', 24.2, (SELECT id FROM estados WHERE sigla = 'RJ')),
('Parnamirim', 25.2, (SELECT id FROM estados WHERE sigla = 'RN')),
('Natal', 15.5, (SELECT id FROM estados WHERE sigla = 'RN')),
('Mossoró', 24.2, (SELECT id FROM estados WHERE sigla = 'RN')),
('São Gonçalo do Amarante', 9.2, (SELECT id FROM estados WHERE sigla = 'RN')),
('Macaíba', 9.2, (SELECT id FROM estados WHERE sigla = 'RN')),
('Porto Alegre', 50.6, (SELECT id FROM estados WHERE sigla = 'RS')),
('Caxias do Sul', 7.9, (SELECT id FROM estados WHERE sigla = 'RS')),
('Pelotas', 25.2, (SELECT id FROM estados WHERE sigla = 'RS')),
('Santa Maria', 15.5, (SELECT id FROM estados WHERE sigla = 'RS')),
('Canoas', 24.2, (SELECT id FROM estados WHERE sigla = 'RS')),
('Porto Velho', 9.2, (SELECT id FROM estados WHERE sigla = 'RO')),
('Ji-Paraná', 25.2, (SELECT id FROM estados WHERE sigla = 'RO')),
('Ariquemes', 15.5, (SELECT id FROM estados WHERE sigla = 'RO')),
('Vilhena', 24.2, (SELECT id FROM estados WHERE sigla = 'RO')),
('Cacoal', 7.9, (SELECT id FROM estados WHERE sigla = 'RO')),
('Boa Vista', 25.2, (SELECT id FROM estados WHERE sigla = 'RR')),
('Rorainópolis', 15.5, (SELECT id FROM estados WHERE sigla = 'RR')),
('Caracaraí', 24.2, (SELECT id FROM estados WHERE sigla = 'RR')),
('Alto Alegre', 24.2, (SELECT id FROM estados WHERE sigla = 'RR')),
('Mucajaí', 9.2, (SELECT id FROM estados WHERE sigla = 'RR')),
('Joinville', 50.6, (SELECT id FROM estados WHERE sigla = 'SC')),
('Florianópolis', 7.9, (SELECT id FROM estados WHERE sigla = 'SC')),
('Blumenau', 25.2, (SELECT id FROM estados WHERE sigla = 'SC')),
('São José', 15.5, (SELECT id FROM estados WHERE sigla = 'SC')),
('Chapecó', 24.2, (SELECT id FROM estados WHERE sigla = 'SC')),
('São Paulo', 9.2, (SELECT id FROM estados WHERE sigla = 'SP')),
('Guarulhos', 25.2, (SELECT id FROM estados WHERE sigla = 'SP')),
('Campinas', 15.5, (SELECT id FROM estados WHERE sigla = 'SP')),
('São Bernardo do Campo', 24.2, (SELECT id FROM estados WHERE sigla = 'SP')),
('Santo André', 7.9, (SELECT id FROM estados WHERE sigla = 'SP')),
('Aracaju', 25.2, (SELECT id FROM estados WHERE sigla = 'SE')),
('Nossa Senhora do Socorro', 15.5, (SELECT id FROM estados WHERE sigla = 'SE')),
('Lagarto', 24.2, (SELECT id FROM estados WHERE sigla = 'SE')),
('Itabaiana', 24.2, (SELECT id FROM estados WHERE sigla = 'SE')),
('São Cristovão', 9.2, (SELECT id FROM estados WHERE sigla = 'SE')),
('Palmas', 25.2, (SELECT id FROM estados WHERE sigla = 'TO')),
('Araguaína', 15.5, (SELECT id FROM estados WHERE sigla = 'TO')),
('Gurupi', 24.2, (SELECT id FROM estados WHERE sigla = 'TO')),
('Porto Nacional', 24.2, (SELECT id FROM estados WHERE sigla = 'TO')),
('Paraíso do Tocantins', 9.2, (SELECT id FROM estados WHERE sigla = 'TO'));



